name: Luqi Docker Image

on:
  push:
    paths:
      - '鹿棋/*'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: "鹿棋棋谱播放"
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/zhc7/chess/luqi:latest 鹿棋
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/zhc7/chess/luqi:latest
